In [1]:
import tensorflow as tf
from trainingUtils import save, load
from layers import AdaIN
import scipy.io as sio
import numpy as np
import os
from preprocessing import DataStream
import matplotlib.pyplot as plt
from init_weights import encoder_weights, decoder_weights
from tqdm import tqdm
from Model import Model
%matplotlib inline

In [2]:
print(DataStream.readNib("../healthy-axis2-slice100/002a07ab7120c861a1a2372c34013fc8c4ec65ae3b0e74571fde0ed3/t1w.nii.gz").shape)

(192, 224, 1)


In [3]:
a = np.zeros(shape = (3,3), dtype = np.float32)

In [4]:
a[1,1] = 1

In [5]:
a

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]], dtype=float32)

In [6]:
b = np.transpose(np.tile(a, (12,16,1,1)))
b.shape

(3, 3, 16, 12)

In [7]:
weights = sio.loadmat("weights.mat")

In [8]:
newdict = {}
for id_w in weights:
    if "conv_" and not "b" in id_w:
        shape = np.array(weights[id_w]).shape
        if len(shape)==4:
            h,w,i,o = shape
            print(h,w,i,o)
            print(np.transpose(np.tile(a,(o,i,1,1))).shape)
            newdict[id_w]=np.transpose(np.tile(a,(o,i,1,1)))
            #newdict[w] = np.transpose(np.tile(a,(o,i,w,h)))
            #print(shape ,w)
    


1 1 3 3
(3, 3, 3, 3)
3 3 3 64
(3, 3, 3, 64)
3 3 64 64
(3, 3, 64, 64)
3 3 64 128
(3, 3, 64, 128)
3 3 128 128
(3, 3, 128, 128)
3 3 128 256
(3, 3, 128, 256)
3 3 256 256
(3, 3, 256, 256)
3 3 256 256
(3, 3, 256, 256)
3 3 256 256
(3, 3, 256, 256)
3 3 256 512
(3, 3, 256, 512)
3 3 512 512
(3, 3, 512, 512)
3 3 512 512
(3, 3, 512, 512)
3 3 512 512
(3, 3, 512, 512)
3 3 512 512
(3, 3, 512, 512)
3 3 512 512
(3, 3, 512, 512)
3 3 512 512
(3, 3, 512, 512)
3 3 512 512
(3, 3, 512, 512)
3 3 512 256
(3, 3, 512, 256)
3 3 256 256
(3, 3, 256, 256)
3 3 256 256
(3, 3, 256, 256)
3 3 256 256
(3, 3, 256, 256)
3 3 256 128
(3, 3, 256, 128)
3 3 128 128
(3, 3, 128, 128)
3 3 128 64
(3, 3, 128, 64)
3 3 64 64
(3, 3, 64, 64)
3 3 64 3
(3, 3, 64, 3)
3 3 512 256
(3, 3, 512, 256)
3 3 256 256
(3, 3, 256, 256)
3 3 256 256
(3, 3, 256, 256)
3 3 256 256
(3, 3, 256, 256)
3 3 256 128
(3, 3, 256, 128)
3 3 128 128
(3, 3, 128, 128)
3 3 128 64
(3, 3, 128, 64)
3 3 64 64
(3, 3, 64, 64)
3 3 64 3
(3, 3, 64, 3)


In [11]:
for w in newdict:
    print(w)
    print(newdict[w][:,:,1,1])

./tf-AdaIN-master/vgg_normalised.t7/conv2d_0
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_2
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_5
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_9
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_12
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_16
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_19
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_22
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_25
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_29
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_32
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-AdaIN-master/vgg_normalised.t7/conv2d_35
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]
./tf-Ada

In [13]:
sio.savemat("project_mask.mat", newdict)